"""Extract line items from estimates previously generated by this app."""

from __future__ import annotations

import io
import re
from typing import Any

ACTION_LABELS = [
    ("remove, install plus materials", "replace_material"),
    ("remove and install", "replace"),
    ("install plus materials", "install_material"),
    ("install only", "install"),
    ("demolition only", "demo"),
    ("material only", "material"),
]

UNITS = ("SQ", "SF", "LF", "EA", "HR", "CY", "LS", "BAG", "PC", "BF", "SY")
MONEY_RE = re.compile(r"^-?\$?\s*\d{1,3}(?:,\d{3})*(?:\.\d{1,2})?$|^-?\$?\s*\d+(?:\.\d{1,2})?$")
QTY_RE = re.compile(r"^-?\d{1,6}(?:,\d{3})*(?:\.\d{1,4})?$")
STOP_RE = re.compile(
    r"^(terms and exclusions|pricing terms|payment instructions|signatures|"
    r"thank you for your business|document generated|grand total|amount paid|"
    r"make check payable|zelle|bank transfer|online payment)\b",
    re.I,
)
HEADER_RE = re.compile(r"^(code|action|work|description|qty|quantity|unit|price|tax|subtotal|\(\$?\)|%\))$", re.I)
SCOPE_RE = re.compile(r"scope\s+of\s+work|invoice\s+items|alcance\s+del\s+trabajo", re.I)
ROW_NUM_RE = re.compile(
    r"^(\d+)\.\s+(.+?)\s+(\d{1,5}(?:,\d{3})*(?:\.\d{1,2})?)\s+(SQ|SF|LF|EA|HR|BF|SY)\s+(\d{1,4}(?:,\d{3})*(?:\.\d{2})?)",
    re.I,
)


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def _money(text: str) -> float | None:
    raw = _norm(text).replace("$", "").replace("USD", "").replace("usd", "").strip()
    raw = raw.replace(" ", "")
    if not raw or not re.search(r"\d", raw):
        return None
    raw = raw.replace(",", "")
    try:
        return float(raw)
    except ValueError:
        return None


def _qty(text: str) -> float | None:
    raw = _norm(text).replace(",", "")
    if not QTY_RE.match(_norm(text)) and not re.fullmatch(r"-?\d+(?:\.\d+)?", raw):
        return None
    try:
        return float(raw)
    except ValueError:
        return None


def _unit(text: str) -> str:
    token = _norm(text).upper().replace(".", "")
    aliases = {
        "SQFT": "SF",
        "SQ FT": "SF",
        "SF": "SF",
        "SQ": "SQ",
        "LF": "LF",
        "EA": "EA",
        "HR": "HR",
        "CY": "CY",
        "LS": "LS",
        "BAG": "BAG",
        "PC": "PC",
        "PCS": "PC",
        "BF": "BF",
        "SY": "SY",
        "UNIT": "EA",
    }
    return aliases.get(token, token if token in UNITS else "")


def _action_key(text: str) -> str:
    blob = _norm(text).lower().replace(" ,", ",")
    for label, key in ACTION_LABELS:
        if blob == label or blob.startswith(label):
            return key
    if "demolition" in blob or blob == "demo":
        return "demo"
    if "material only" in blob:
        return "material"
    if "install plus" in blob:
        return "install_material"
    if "install only" in blob:
        return "install"
    if "remove" in blob and "install" in blob:
        return "replace_material" if "material" in blob else "replace"
    return ""


def _words_pymupdf(pdf_bytes: bytes) -> list[dict[str, Any]]:
    import fitz

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    out: list[dict[str, Any]] = []
    try:
        for page_i, page in enumerate(doc):
            height = float(page.rect.height or 792)
            for item in page.get_text("words") or []:
                if len(item) < 5:
                    continue
                x0, y0, x1, y1, text = item[:5]
                token = _norm(str(text))
                if not token:
                    continue
                out.append(
                    {
                        "page": page_i,
                        "x0": float(x0),
                        "y0": float(y0),
                        "x1": float(x1),
                        "y1": float(y1),
                        "xc": (float(x0) + float(x1)) / 2.0,
                        "yc": (float(y0) + float(y1)) / 2.0 + page_i * (height + 40),
                        "text": token,
                    }
                )
    finally:
        doc.close()
    out.sort(key=lambda w: (w["page"], w["yc"], w["x0"]))
    return out


def _cluster_rows(words: list[dict[str, Any]], y_tol: float = 7.5) -> list[list[dict[str, Any]]]:
    rows: list[list[dict[str, Any]]] = []
    for word in words:
        if rows and abs(word["yc"] - rows[-1][0]["yc"]) <= y_tol and word["page"] == rows[-1][0]["page"]:
            rows[-1].append(word)
        else:
            rows.append([word])
    for row in rows:
        row.sort(key=lambda w: w["x0"])
    return rows


def _row_text(row: list[dict[str, Any]]) -> str:
    return _norm(" ".join(w["text"] for w in row))


def _find_scope_index(rows: list[list[dict[str, Any]]]) -> int:
    for i, row in enumerate(rows):
        if SCOPE_RE.search(_row_text(row)):
            return i
    return 0


def _is_header_row(text: str) -> bool:
    low = text.lower()
    has_code = "code" in low or "código" in low or "codigo" in low
    has_qty = "qty" in low or "quantity" in low or "cant" in low
    has_desc = "description" in low or "descripción" in low or "descripcion" in low or "work description" in low
    has_unit = "unit" in low or "unidad" in low
    return has_code and has_qty and (has_desc or has_unit)


def _header_columns(row: list[dict[str, Any]]) -> dict[str, tuple[float, float]] | None:
    tokens = [(w["text"].lower(), w["x0"], w["x1"], w["xc"]) for w in row]
    joined = " ".join(t[0] for t in tokens)
    if not _is_header_row(joined):
        return None

    def find_name(*names: str) -> tuple[float, float] | None:
        for name in names:
            for i, (txt, x0, x1, xc) in enumerate(tokens):
                if txt == name:
                    return (x0, x1)
                if i + 1 < len(tokens) and f"{txt} {tokens[i + 1][0]}" == name:
                    return (x0, tokens[i + 1][2])
        return None

    code = find_name("code", "código", "codigo")
    action = find_name("action", "acción", "accion")
    desc = find_name("work description", "description", "descripción", "descripcion", "work")
    qty = find_name("qty", "quantity", "cant")
    # First "unit" that is not the start of "unit price"
    unit = None
    unit_price = None
    for i, (txt, x0, x1, xc) in enumerate(tokens):
        nxt = tokens[i + 1][0] if i + 1 < len(tokens) else ""
        if txt == "unit" and nxt.startswith("price"):
            end = tokens[i + 1][2]
            if i + 2 < len(tokens) and tokens[i + 2][0] in {"($)", "$", "(%)"}:
                end = tokens[i + 2][2]
            unit_price = (x0, end)
        elif txt in {"unit", "unidad"} and unit is None and nxt not in {"price", "($)"}:
            unit = (x0, x1)
        elif txt == "price" and unit_price is None:
            unit_price = (x0, x1)
    tax = find_name("tax")
    subtotal = find_name("subtotal")
    if not (desc and qty and (unit or unit_price)):
        return None
    named = {
        "code": code,
        "action": action,
        "description": desc,
        "qty": qty,
        "unit": unit,
        "unit_price": unit_price,
        "tax": tax,
        "subtotal": subtotal,
    }
    ordered = [(k, v) for k, v in named.items() if v]
    ordered.sort(key=lambda kv: kv[1][0])
    bands: dict[str, tuple[float, float]] = {}
    for i, (key, (x0, x1)) in enumerate(ordered):
        left = x0 if i == 0 else (ordered[i - 1][1][1] + x0) / 2.0
        right = x1 if i == len(ordered) - 1 else (x1 + ordered[i + 1][1][0]) / 2.0
        if i == 0:
            left = min(left, x0 - 8)
        if i == len(ordered) - 1:
            right = max(right, x1 + 80)
        bands[key] = (left, right)
    return bands


def _assign_columns(row: list[dict[str, Any]], bands: dict[str, tuple[float, float]]) -> dict[str, str]:
    buckets = {k: [] for k in bands}
    leftovers = []
    for word in row:
        placed = False
        for key, (left, right) in bands.items():
            if left <= word["xc"] <= right:
                buckets[key].append(word["text"])
                placed = True
                break
        if not placed:
            leftovers.append(word)
    if leftovers:
        desc_band = bands.get("description")
        for word in leftovers:
            if desc_band and word["xc"] < bands.get("qty", (9999, 9999))[0]:
                buckets.setdefault("description", []).append(word["text"])
    return {k: _norm(" ".join(v)) for k, v in buckets.items()}


def _skip_row(text: str) -> bool:
    if not text:
        return True
    if STOP_RE.search(text):
        return True
    if HEADER_RE.fullmatch(text):
        return True
    if _is_header_row(text):
        return True
    if SCOPE_RE.search(text) and len(text) < 40:
        return True
    if re.match(r"^(subtotal|overhead|profit|tax)\b", text, re.I) and "$" in text:
        return True
    return False


def _is_area_title(cols: dict[str, str], full: str) -> bool:
    qty = _qty(cols.get("qty") or "")
    price = _money(cols.get("unit_price") or "")
    unit = _unit(cols.get("unit") or "")
    if qty is not None or price is not None or unit:
        return False
    if _action_key(cols.get("action") or full):
        return False
    if re.match(r"^\d+\.\s+\S+", full):
        return True
    if re.search(r"\([^)]*\)\s*$", full) and len(full) < 80:
        return True
    return False


def _clean_area_title(text: str) -> str:
    title = re.sub(r"^\d+\.\s*", "", _norm(text))
    title = re.sub(r"\(\s*\)\s*$", "", title).strip()
    title = re.sub(r"\(\s*(.+?)\s*\)$", r"(\1)", title)
    return title or "Imported line items"


def _item_from_cols(cols: dict[str, str]) -> dict[str, Any] | None:
    desc = _norm(cols.get("description") or "")
    code = _norm(cols.get("code") or "")
    action_raw = _norm(cols.get("action") or "")
    qty = _qty(cols.get("qty") or "")
    unit = _unit(cols.get("unit") or "")
    unit_price = _money(cols.get("unit_price") or "")
    subtotal = _money(cols.get("subtotal") or "")
    tax = _money(cols.get("tax") or "")
    if qty is None and unit_price is None and not unit:
        return None
    if not desc and not code:
        return None
    if unit_price is None and subtotal is not None and qty:
        unit_price = round(subtotal / qty, 2) if qty else None
    return {
        "code": code,
        "action": _action_key(action_raw) or "replace",
        "action_label": action_raw,
        "description": desc,
        "qty": qty if qty is not None else 1.0,
        "unit": unit or "SF",
        "unit_price": float(unit_price or 0),
        "subtotal": float(subtotal) if subtotal is not None else None,
        "tax": float(tax or 0),
    }


def _merge_continuation(item: dict[str, Any], cols: dict[str, str], full: str) -> bool:
    qty = _qty(cols.get("qty") or "")
    price = _money(cols.get("unit_price") or "")
    unit = _unit(cols.get("unit") or "")
    if qty is not None or price is not None or unit:
        return False
    extra_desc = _norm(cols.get("description") or "")
    extra_action = _norm(cols.get("action") or "")
    extra_code = _norm(cols.get("code") or "")
    bits = []
    if extra_code and extra_code.lower() not in (item.get("code") or "").lower():
        if not _action_key(extra_code):
            bits.append(extra_code)
    if extra_action:
        current = _norm(item.get("action_label") or "")
        combined = _norm(f"{current} {extra_action}")
        mapped = _action_key(combined)
        if mapped and mapped != _action_key(current):
            item["action_label"] = combined
            item["action"] = mapped
        elif not _action_key(extra_action):
            bits.append(extra_action)
        else:
            item["action_label"] = combined or extra_action
            item["action"] = mapped or item.get("action") or "replace"
    if extra_desc:
        bits.append(extra_desc)
    if not bits and full and not _is_header_row(full):
        bits.append(full)
    if not bits:
        return False
    item["description"] = _norm(f"{item.get('description') or ''} {' '.join(bits)}")
    return True


def extraer_partidas_estimado(pdf_bytes: bytes) -> dict[str, Any]:
    words = _words_pymupdf(pdf_bytes)
    rows = _cluster_rows(words)
    start = _find_scope_index(rows)
    bands = None
    areas: list[dict[str, Any]] = []
    current_title = "Imported line items"
    current_items: list[dict[str, Any]] = []

    def flush_area():
        nonlocal current_items, current_title
        if current_items:
            areas.append({"title": current_title, "items": current_items})
            current_items = []

    for row in rows[start:]:
        text = _row_text(row)
        if STOP_RE.search(text) and bands:
            break
        header_bands = _header_columns(row)
        if header_bands:
            bands = header_bands
            continue
        if not bands:
            continue
        if _skip_row(text):
            continue
        cols = _assign_columns(row, bands)
        if _is_area_title(cols, text):
            flush_area()
            current_title = _clean_area_title(text)
            continue
        item = _item_from_cols(cols)
        if item:
            current_items.append(item)
            continue
        if current_items and _merge_continuation(current_items[-1], cols, text):
            continue

    flush_area()
    items = []
    for area in areas:
        for it in area["items"]:
            packed = dict(it)
            packed["area"] = area["title"]
            items.append(packed)
    if not items:
        items = _fallback_text_parse(pdf_bytes)
        if items:
            areas = [{"title": "Imported line items", "items": items}]
    return {
        "success": True,
        "count": len(items),
        "items": items,
        "areas": areas,
    }


def _fallback_text_parse(pdf_bytes: bytes) -> list[dict[str, Any]]:
    text = ""
    try:
        import fitz

        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        try:
            text = "\n".join(page.get_text() or "" for page in doc)
        finally:
            doc.close()
    except Exception:
        try:
            from pdfminer.high_level import extract_text

            text = extract_text(io.BytesIO(pdf_bytes)) or ""
        except Exception:
            return []
    lines = [_norm(l) for l in text.splitlines() if _norm(l)]
    start = 0
    for i, line in enumerate(lines):
        if SCOPE_RE.search(line):
            start = i + 1
            break
    action_alt = "|".join(re.escape(lbl) for lbl, _ in ACTION_LABELS)
    unit_alt = "|".join(UNITS)
    row_re = re.compile(
        rf"^(?P<code>[A-Z0-9][\w./-]{{0,18}})?\s*(?P<action>{action_alt})\s+"
        rf"(?P<desc>.+?)\s+(?P<qty>\d{{1,6}}(?:,\d{{3}})*(?:\.\d{{1,4}})?)\s+"
        rf"(?P<unit>{unit_alt})\s+(?P<price>\$?\s*\d{{1,3}}(?:,\d{{3}})*(?:\.\d{{2}})|\d+(?:\.\d{{2}}))"
        rf"(?:\s+(?P<tax>\d+(?:\.\d+)?))?\s*(?P<subtotal>\$?\s*\d{{1,3}}(?:,\d{{3}})*(?:\.\d{{2}}))?",
        re.I,
    )
    items: list[dict[str, Any]] = []
    pending = ""
    for line in lines[start:]:
        if STOP_RE.search(line):
            break
        if _is_header_row(line) or SCOPE_RE.search(line):
            continue
        blob = _norm(f"{pending} {line}") if pending else line
        match = row_re.search(blob)
        if not match:
            if items and not QTY_RE.match(line) and not MONEY_RE.match(line.replace(" ", "")):
                items[-1]["description"] = _norm(f"{items[-1]['description']} {line}")
            else:
                pending = blob
            continue
        pending = ""
        items.append(
            {
                "code": _norm(match.group("code") or ""),
                "action": _action_key(match.group("action")) or "replace",
                "action_label": _norm(match.group("action")),
                "description": _norm(match.group("desc")),
                "qty": _qty(match.group("qty")) or 1.0,
                "unit": _unit(match.group("unit")) or "SF",
                "unit_price": _money(match.group("price")) or 0.0,
                "subtotal": _money(match.group("subtotal") or ""),
                "tax": _money(match.group("tax") or "") or 0.0,
                "area": "Imported line items",
            }
        )
    return items


def extraer_texto_pdf(pdf_bytes: bytes) -> str:
    try:
        import fitz

        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        try:
            return "\n".join(page.get_text() or "" for page in doc)
        finally:
            doc.close()
    except Exception:
        pass
    try:
        from pdfminer.high_level import extract_text

        return extract_text(io.BytesIO(pdf_bytes)) or ""
    except Exception:
        return ""


def es_tabla_scope_of_work(texto: str) -> bool:
    blob = re.sub(r"\s+", " ", str(texto or "")).upper()
    return (
        "SCOPE OF WORK" in blob
        and re.search(r"\bCODE\b", blob) is not None
        and re.search(r"\bACTION\b", blob) is not None
        and "WORK DESCRIPTION" in blob
    )


def extraer_partidas_numeradas(texto: str) -> dict[str, Any]:
    raw = [_norm(line) for line in str(texto or "").splitlines() if _norm(line)]
    fused: list[str] = []
    i = 0
    while i < len(raw):
        line = raw[i]
        consumed = i
        if re.match(r"^\d+\.\s+", line) and not ROW_NUM_RE.match(line):
            combined = line
            for j in range(i + 1, min(i + 5, len(raw))):
                combined = f"{combined} {raw[j]}"
                if ROW_NUM_RE.match(combined):
                    line = combined
                    consumed = j
                    break
        fused.append(line)
        i = consumed + 1
    items: list[dict[str, Any]] = []
    for line in fused:
        if re.match(
            r"^(totals?|recap|summary|overhead|profit|net claim|material sales tax|subtotal|line item totals)",
            line,
            re.I,
        ):
            continue
        if re.search(r"totals?:|O&P|Replacement Cost|Coverage", line, re.I):
            continue
        match = ROW_NUM_RE.match(line)
        if not match:
            continue
        qty = float(str(match.group(3)).replace(",", "")) if match.group(3) else 1.0
        price = float(str(match.group(5)).replace(",", "")) if match.group(5) else 0.0
        items.append(
            {
                "code": match.group(1),
                "action": "install",
                "description": match.group(2).strip(),
                "qty": qty,
                "unit": match.group(4).upper(),
                "unit_price": price,
            }
        )
    return {"success": True, "items": items, "lines": fused, "count": len(items)}


def enrutar_importacion_pdf(pdf_bytes: bytes) -> dict[str, Any] | None:
    """Pick SCOPE OF WORK table parser vs numbered Xactimate-style lines. None = unknown format."""
    texto = extraer_texto_pdf(pdf_bytes)
    if es_tabla_scope_of_work(texto):
        payload = extraer_partidas_estimado(pdf_bytes)
        payload["parser"] = "scope_of_work"
        payload["document_type"] = "past_estimate"
        return payload
    numeradas = extraer_partidas_numeradas(texto)
    if numeradas.get("items"):
        numeradas["parser"] = "numbered_items"
        numeradas["document_type"] = "numbered_items"
        return numeradas
    return None
